Tried to refactor by moving functionality around into different modules to make way for the compound AES implementation that checks the processor flags.  HOWEVER now I'm running into odd link problems.
  Linking dist/build/benchmark-intel-aes-rng/benchmark-intel-aes-rng ...
  dist/build/benchmark-intel-aes-rng/benchmark-intel-aes-rng-tmp/Main.o: In function `sqM1_info':
  (.text+0xbb0a): undefined reference to `intelzmaeszm0zi1zi1_CodecziCryptoziConvertRNG_CRGtoRG0_con_info'